### ISSUE TITLE
High and Low avaiable?

### ISSUE THREAD

**Issue by stpietsch** [kriszyp/ordered-binary#1]
Is there a posibility to get a lowest and highest possible value? 
This would help querying the data in for example LevelDB or LMDB. Actually this exists for example in "bytewise" and "charwise" packages...

Actually I don't know how to query "lmdb-store" and include the last possible value with these keys ():

- ["person", 1]
- ["person", 2]
- ["person", 3]

Know how too query this data, if I don't know the highest number?
```js
db.getRange({
      start: ["person", 0]
      ,end: ["person", ???????]
})
```
with charwise / bytewise there always have been null/undefined to make a placeholder for highest and lowest value:
```js
db.getRange({
      start: ["person", null]
      ,end: ["person", undefined]
})
```

**Comment by kriszyp** [comment]
Because of the fact that all values can just translate to binary ordering and because you can directly provide a buffer as a key value, the lowest value is: `Buffer.from([0])` and the highest would be `Buffer.from([0xff, 0xff,...])`. Technically a buffer that is the maximum key size filled with 0xff would be the highest available, but that is only competitive with other direct buffers. For JS primitive values that are encoded with ordered-binary, UTF-8 strings are the highest and the highest valid initial byte for UTF-8 is 0xf8, so `Buffer.from([0xff])` is sufficient to be higher than any encoded JS primitive value.

I could certainly provide these as exported constants.

**Comment by stpietsch** [comment]
Wow, thanks for the quick response and works this way like charm. 
I think exported constants would be nice or just write it down in the README. There is a good explanation in https://github.com/DoctorEvidence/lmdb-store about the order, so why not take this and use it in this Repo too, extend by those two values:

```
Buffer.from([0])
Symbol.for('even symbols')
-10 // negative supported
-1.1 // decimals supported
400
3E10
'Hello'
['Hello', 'World']
'World'
'hello'
['hello', 1, 'world']
['hello', 'world']
Buffer.from([0xff])
```
